### PR TITLE
Working

### PR DESCRIPTION
**Pull request by BSGreaves**
@drdreed This one's ready.

### CODE REVIEW

**Review by DevDreed — CHANGES_REQUESTED** [review]
The third element contains the product availability (e.g. "Available" or "Not Available")

This section should have a header containing the word "Specifications"

I know these are petty items but its what the requirements suggest should be in the particular elements.

**Comment by BSGreaves** [comment]
@drdreed 
No worries, I like all feedback! However... In these instances I think I've met the requirements.

"The third element contains the product availability (e.g. "Available" or "Not Available")"
This element (which is a p element of class 'block' which makes it a block level element) is on line 17:
`<p class="availability block">Availability</p>`

"This section should have a header containing the word "Specifications""
The section 2 header is on line 20 and is wrapped in the header element.
`<header class="sec2header">Header - Specifications</header>`

Let me attach some screen caps to show my version against the mockup provided in the instructions

screen shot 2017-02-08 at 3 40 43 pm
screen shot 2017-02-08 at 3 40 21 pm

**Comment by DevDreed** [comment]
I will leave that one up to you and Zoe.  When I did this assignment I made it look exactly like the example.  All the prices and everything were filled out correctly.

**Comment by DevDreed** [comment]
👍

**Review by DevDreed — APPROVED** [review]
👍

**Pull request merged**
